[server]
address = "localhost:8080"

[tracker]
address = "0.0.0.0:9000"

[tracker.mappings]
0 = ""
1 = ""
2 = ""
3 = ""
4 = ""
5 = ""
6 = ""
7 = ""
8 = ""
9 = ""
10 = ""
11 = ""
12 = ""
13 = ""
14 = ""
15 = ""